/*globals window*/
(function () {
    'use strict';
    var bandBlocksSamples = {},
        sampleOptions = [];

    sampleOptions.push(['natScale', 'Natural Scale']);
    bandBlocksSamples.natScale = '<xml xmlns="http://www.w3.org/1999/xhtml"><block type="variables_set" id="x-70`8IrZ^ClTqN:~E5l" x="184" y="70"><field name="VAR">note</field><value name="VALUE"><block type="sound" id="7{5:p%E`Lb^4_79Rq0(~"><field name="NOTE">C</field><field name="OCTAVE">4</field><field name="MOD">NATURAL</field></block></value><next><block type="controls_repeat_ext" id="qqjdsXZ|~j.LXe[A:g+!"><value name="TIMES"><shadow type="math_number" id="7`N@FvW*x,vCIJw//+`d"><field name="NUM">24</field></shadow></value><statement name="DO"><block type="play" id=",dh,;mo:om{g2;@s@I7q"><field name="RHYTHM">QUARTER</field><value name="NOTE"><block type="variables_get" id="%i.wlyK^%-DEEv[z@cIf"><field name="VAR">note</field></block></value><next><block type="variables_set" id="zRmQf%xE|Iq7)~JX^+#;"><field name="VAR">note</field><value name="VALUE"><block type="nextNote" id="worxeR=y6)d|lDgcsm^/"><value name="NOTE"><block type="variables_get" id="F1~i+{UNvVdTHK?Df?rH"><field name="VAR">note</field></block></value></block></value></block></next></block></statement></block></next></block></xml>';

    sampleOptions.push(['majorScale', 'Major Scale']);
    bandBlocksSamples.majorScale = '<xml xmlns="http://www.w3.org/1999/xhtml"><block type="variables_set" id="x-70`8IrZ^ClTqN:~E5l" x="184" y="70"><field name="VAR">note</field><value name="VALUE"><block type="sound" id="7{5:p%E`Lb^4_79Rq0(~"><field name="NOTE">C</field><field name="OCTAVE">4</field><field name="MOD">NATURAL</field></block></value><next><block type="variables_set" id="hr8vx(iqr$D{ZmVYg^Dj"><field name="VAR">steps</field><value name="VALUE"><block type="lists_create_with" id="MHj=5~/qUKFf4e@/Zv(:"><mutation items="7"></mutation><value name="ADD0"><block type="math_number" id="Mw}7@A7l;Y4nzXd6L*};"><field name="NUM">2</field></block></value><value name="ADD1"><block type="math_number" id="fyjKf(6(mRu(B(5b1oQn"><field name="NUM">2</field></block></value><value name="ADD2"><block type="math_number" id="(9n=HK.vK4Ve{b1z=yG:"><field name="NUM">1</field></block></value><value name="ADD3"><block type="math_number" id="KtOq^`UvEOc/Rkf6IH;{"><field name="NUM">2</field></block></value><value name="ADD4"><block type="math_number" id="0h251ltAK|t?yxR#D/X-"><field name="NUM">2</field></block></value><value name="ADD5"><block type="math_number" id="ZlRee3V,`F,JIHw5Q=I`"><field name="NUM">2</field></block></value><value name="ADD6"><block type="math_number" id="Hr^ze(f^?YBcWeisTO~y"><field name="NUM">1</field></block></value></block></value><next><block type="controls_forEach" id="1AmAS3SAs8nG%,l?}}Yo"><field name="VAR">stepCount</field><value name="LIST"><block type="variables_get" id="mi%UwPMlWaP9p`Fx{P;x"><field name="VAR">steps</field></block></value><statement name="DO"><block type="play" id=",dh,;mo:om{g2;@s@I7q"><field name="RHYTHM">QUARTER</field><value name="NOTE"><block type="variables_get" id="%i.wlyK^%-DEEv[z@cIf"><field name="VAR">note</field></block></value><next><block type="controls_repeat_ext" id="qqjdsXZ|~j.LXe[A:g+!"><value name="TIMES"><shadow type="math_number" id="7`N@FvW*x,vCIJw//+`d"><field name="NUM">24</field></shadow><block type="variables_get" id="uY^o,gr|c4!{aAfI^JhT"><field name="VAR">stepCount</field></block></value><statement name="DO"><block type="variables_set" id="zRmQf%xE|Iq7)~JX^+#;"><field name="VAR">note</field><value name="VALUE"><block type="nextNote" id="worxeR=y6)d|lDgcsm^/"><value name="NOTE"><block type="variables_get" id="F1~i+{UNvVdTHK?Df?rH"><field name="VAR">note</field></block></value></block></value></block></statement></block></next></block></statement></block></next></block></next></block></xml>';

    window.bandBlocksSamples = {
        samples: bandBlocksSamples,
        options: sampleOptions
    };
}());
